
[[dependencies]]
  branch = "master"
  name = "github.com/Xe/uuid"

[[dependencies]]
  branch = "master"
  name = "github.com/asdine/storm"

[[dependencies]]
  branch = "master"
  name = "github.com/golang/mock"

[[dependencies]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/crypto"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/net"

[[dependencies]]
  branch = "master"
  name = "google.golang.org/grpc"
